# Generated by Django 2.0.1 on 2018-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='index',
        ),
        migrations.AddField(
            model_name='upcoming',
            name='thumbimage',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='addon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='title',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
