# Generated by Django 2.0.1 on 2018-04-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180421_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcoming',
            old_name='thumbimage',
            new_name='thumbnailImage',
        ),
    ]
