# Generated by Django 2.0.1 on 2018-04-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180421_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='isFolder',
        ),
    ]
