# Generated by Django 2.0.1 on 2018-04-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_upcoming_isfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelExcludeFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('value', models.CharField(default='', max_length=2000)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excludefilters', to='web.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelIncludeFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('value', models.CharField(default='', max_length=2000)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='includefilters', to='web.Channel')),
            ],
        ),
    ]
