# Generated by Django 2.0.1 on 2018-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180427_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='starttime',
            field=models.IntegerField(default=0),
        ),
    ]
