# Generated by Django 2.0.1 on 2018-05-03 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_upcoming_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='upfill_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='upfill_lastfail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='upfill_lastrun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='upfill_lastsuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
