# Generated by Django 2.0.1 on 2018-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180503_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='upfill_errorcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
