# Generated by Django 2.0.1 on 2018-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_upcoming_playback_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='adultmode',
            field=models.CharField(default='noadult', max_length=200),
        ),
    ]
